version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend:/app
      - ../src:/app/src  # Mount the src directory
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
